"""
Analytic forward solution for a multi-shell spherical head model.

Implements the multi-shell series solution for the electric potential
at the scalp due to a current dipole inside a concentric four-shell
spherical conductor (brain/CSF/skull/scalp).

References
----------
de Munck, J.C. (1988). The potential distribution in a layered anisotropic
    spheroidal volume conductor. J. Appl. Phys. 64(2):464-470.
Mosher, J.C., Leahy, R.M., & Lewis, P.S. (1999). EEG and MEG: forward
    solutions for inverse methods. IEEE Trans. Biomed. Eng. 46(3):245-259.
Zhang, Z. (1995). A fast method to compute surface potentials generated by
    dipoles within multilayer anisotropic spheres. Phys. Med. Biol.
    40(3):335-349.

Why this exists
---------------
The forward problem on a sphere has a *closed-form analytic* solution. This
matters because:
  1. We can generate "scalp data" without using any numerical solver.
  2. Inverse-method errors are then *purely* due to the inverse method,
     not to forward-model discretization error.
  3. It serves as a unit test: if my inverse code can't recover a known
     dipole from analytic scalp data, my inverse code has bugs.

This is Question A in the validation hierarchy.

Numerical notes
---------------
We work in *normalized* coordinates (radii relative to head radius R) to
avoid overflow at high series order. Inputs/outputs use physical units
(mm for positions, AÂ·m for dipole moments, V for potentials).
"""
from __future__ import annotations
import numpy as np
import os
from dataclasses import dataclass
from typing import Tuple
from scipy.special import lpmv


DEFAULT_RADII_MM = (81.0, 85.0, 87.0, 92.0)   # brain, CSF, skull, scalp
DEFAULT_SIGMAS = (0.33, 1.79, 0.0042, 0.33)    # S/m


@dataclass
class SphericalHeadModel:
    """Concentric-spheres head model. Radii in mm, conductivities in S/m."""
    radii_mm: Tuple[float, ...] = DEFAULT_RADII_MM
    sigmas: Tuple[float, ...] = DEFAULT_SIGMAS

    def __post_init__(self) -> None:
        if len(self.radii_mm) != len(self.sigmas):
            raise ValueError("radii_mm and sigmas must have same length")
        if not all(r1 < r2 for r1, r2 in zip(self.radii_mm, self.radii_mm[1:])):
            raise ValueError("radii_mm must be strictly increasing")
        if any(s <= 0 for s in self.sigmas):
            raise ValueError("conductivities must be positive")

    @property
    def n_shells(self) -> int:
        return len(self.radii_mm)

    @property
    def head_radius_mm(self) -> float:
        return self.radii_mm[-1]

    def normalized_radii(self) -> np.ndarray:
        return np.array(self.radii_mm) / self.head_radius_mm


def _series_coefficients(model: SphericalHeadModel, n_terms: int = 60) -> np.ndarray:
    """
    Compute series coefficients c_n via transfer-matrix recursion in
    normalized coordinates (avoids overflow at high n).
    """
    sigmas = np.array(model.sigmas, dtype=float)
    rho = model.normalized_radii()
    K = len(sigmas)
    n_arr = np.arange(1, n_terms + 1, dtype=float)
    c = np.zeros(n_terms)

    for idx, n in enumerate(n_arr):
        A, B = 1.0, 0.0
        for k in range(K - 1):
            sig_in, sig_out = sigmas[k], sigmas[k + 1]
            rk = rho[k]
            ratio = sig_in / sig_out
            rkn1 = rk ** (2 * n + 1)
            t11 = (n * ratio + (n + 1)) / (2 * n + 1)
            t12 = (n + 1) * (1 - ratio) / ((2 * n + 1) * rkn1)
            t21 = n * (1 - ratio) * rkn1 / (2 * n + 1)
            t22 = ((n + 1) * ratio + n) / (2 * n + 1)
            A_new = t11 * A + t12 * B
            B_new = t21 * A + t22 * B
            A, B = A_new, B_new

        denom = (n + 1) * (A + B)
        c[idx] = (2 * n + 1) / denom if abs(denom) > 1e-30 else 0.0

    return c


def forward_potential(
    dipole_pos_mm: np.ndarray,
    dipole_moment: np.ndarray,
    electrode_pos_mm: np.ndarray,
    model: SphericalHeadModel | None = None,
    n_terms: int = 60,
) -> np.ndarray:
    """
    Compute scalp potential at each electrode due to a current dipole.

    Returns
    -------
    V : (N,) array of potentials in volts.
    """
    if model is None:
        model = SphericalHeadModel()

    dipole_pos_mm = np.asarray(dipole_pos_mm, dtype=float).reshape(3)
    dipole_moment = np.asarray(dipole_moment, dtype=float).reshape(3)
    electrode_pos_mm = np.asarray(electrode_pos_mm, dtype=float).reshape(-1, 3)

    R = model.head_radius_mm
    r_d = float(np.linalg.norm(dipole_pos_mm))
    if r_d >= model.radii_mm[0]:
        raise ValueError(
            f"Dipole at r={r_d:.1f}mm is outside innermost shell "
            f"(brain radius {model.radii_mm[0]}mm)."
        )

    rho_d = r_d / R

    if r_d < 1e-9:
        rhat_source = np.array([0.0, 0.0, 1.0])
    else:
        rhat_source = dipole_pos_mm / r_d

    moment_radial = float(dipole_moment @ rhat_source)
    moment_tang_vec = dipole_moment - moment_radial * rhat_source
    moment_tang_mag = float(np.linalg.norm(moment_tang_vec))

    elec_r = np.linalg.norm(electrode_pos_mm, axis=1, keepdims=True)
    if np.any(elec_r < 1e-6):
        raise ValueError("Electrode at origin not allowed")
    elec_proj = electrode_pos_mm * (R / elec_r)
    elec_unit = elec_proj / R

    c = _series_coefficients(model, n_terms=n_terms)
    n_arr = np.arange(1, n_terms + 1, dtype=float)

    cos_theta = elec_unit @ rhat_source
    cos_theta = np.clip(cos_theta, -1.0, 1.0)

    if moment_tang_mag > 1e-15 and r_d > 1e-9:
        e_tang = moment_tang_vec / moment_tang_mag
        elec_tang = elec_unit - cos_theta[:, None] * rhat_source[None, :]
        elec_tang_norm = np.linalg.norm(elec_tang, axis=1)
        cos_phi = np.where(
            elec_tang_norm > 1e-12,
            (elec_tang @ e_tang) / np.maximum(elec_tang_norm, 1e-30),
            0.0,
        )
    else:
        cos_phi = np.zeros(elec_unit.shape[0])

    R_m = R * 1e-3
    prefactor = 1.0 / (4 * np.pi * model.sigmas[0] * R_m**2)

    if rho_d > 0:
        depth_pow = rho_d ** (n_arr - 1)
    else:
        depth_pow = np.where(n_arr == 1, 1.0, 0.0)

    V = np.zeros(elec_unit.shape[0])
    for idx, n in enumerate(n_arr):
        n_int = int(n)
        P_n = lpmv(0, n_int, cos_theta)
        P_n1 = lpmv(1, n_int, cos_theta)
        # Radial and tangential dipole components enter at order n with
        # multipole strengths n and 1 respectively (de Munck 1988; Mosher
        # 1999 eq. 22; Yao 2000). With c_n defined as below, the homogeneous
        # limit gives c_n = (2n+1)/(n+1), so the radial surface coefficient
        # (n+1)*c_n = (2n+1) is already correct. The tangential coefficient
        # must therefore be (n+1)/n * c_n so that it equals (2n+1)/n, giving
        # the correct radial:tangential ratio of n:1. (A bare c_n here is too
        # small by n/(n+1) and inflates the radial:tangential ratio to n+1:1;
        # verified to machine precision against the Yao closed form in the
        # homogeneous limit.)
        V += (n + 1) * c[idx] * depth_pow[idx] * P_n * moment_radial
        if moment_tang_mag > 1e-15:
            V += (n + 1) / n * c[idx] * depth_pow[idx] * P_n1 * cos_phi * moment_tang_mag

    return prefactor * V


def make_standard_montage_64(model: SphericalHeadModel | None = None) -> np.ndarray:
    """LEGACY Fibonacci-spiral stand-in: 64 quasi-uniform electrodes on the upper
    hemisphere. The montage-robust results (Q-A..Q-D, Q0) were generated with this.
    For REAL EGI positions (a commercial HD-EEG geodesic net) use
    make_gsn_montage_64 -- used for real-position montage work."""
    if model is None:
        model = SphericalHeadModel()
    R = model.head_radius_mm
    n = 64
    idx = np.arange(n, dtype=float) + 0.5
    phi = np.arccos(1 - idx / n)
    theta = np.pi * (1 + 5**0.5) * idx
    x = R * np.sin(phi) * np.cos(theta)
    y = R * np.sin(phi) * np.sin(theta)
    z = R * np.cos(phi)
    return np.column_stack([x, y, z])


def make_gsn_montage_64(model: SphericalHeadModel | None = None) -> np.ndarray:
    """Real 64-ch EGI HydroCel Geodesic Sensor Net (= a commercial HD-EEG geodesic net) layout,
    projected onto the model scalp sphere. Loads the exported EGI coordinates
    (bandr_inverse/montages/GSN-HydroCel-64.csv; MNE head frame, metres) and radially
    projects each electrode direction onto the sphere of radius model.head_radius_mm,
    preserving the geodesic angular layout. Canonical montage for real-position work
    (channel selection). NB: template geodesic positions, not subject-digitized."""
    if model is None:
        model = SphericalHeadModel()
    R = model.head_radius_mm
    csv = os.path.join(os.path.dirname(__file__), "..", "montages", "GSN-HydroCel-64.csv")
    P = np.loadtxt(csv, delimiter=",", skiprows=1, usecols=(1, 2, 3))   # (64,3) metres
    dirs = P / np.linalg.norm(P, axis=1, keepdims=True)
    return dirs * R
